'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
'
Namespace WSPedido
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSPedidoObtenerSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSPedidoObtener
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PedidoListadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.GF.Portal.UI.WEB.My.MySettings.Default.GF_Portal_UI_WEB_WSPedido_WSPedidoObtener
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event PedidoListadoCompleted As PedidoListadoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PedidoListado", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PedidoListado() As Epedido()
            Dim results() As Object = Me.Invoke("PedidoListado", New Object(-1) {})
            Return CType(results(0),Epedido())
        End Function
        
        '''<remarks/>
        Public Overloads Sub PedidoListadoAsync()
            Me.PedidoListadoAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PedidoListadoAsync(ByVal userState As Object)
            If (Me.PedidoListadoOperationCompleted Is Nothing) Then
                Me.PedidoListadoOperationCompleted = AddressOf Me.OnPedidoListadoOperationCompleted
            End If
            Me.InvokeAsync("PedidoListado", New Object(-1) {}, Me.PedidoListadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnPedidoListadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.PedidoListadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PedidoListadoCompleted(Me, New PedidoListadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Epedido
        
        Private ped_idField As String
        
        Private ped_cli_rucField As String
        
        Private ped_razonSocialField As String
        
        Private ped_fechaField As String
        
        Private ped_totalField As Integer
        
        Private ped_pro_idField As String
        
        Private pro_descripcionField As String
        
        Private ped_precioField As Decimal
        
        Private ped_cantidadField As Integer
        
        Private ped_subTotalField As Decimal
        
        Private situacionField As String
        
        Private estadoField As String
        
        Private desEstadoField As String
        
        Private idUsuarioField As Integer
        
        '''<remarks/>
        Public Property ped_id() As String
            Get
                Return Me.ped_idField
            End Get
            Set
                Me.ped_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_cli_ruc() As String
            Get
                Return Me.ped_cli_rucField
            End Get
            Set
                Me.ped_cli_rucField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_razonSocial() As String
            Get
                Return Me.ped_razonSocialField
            End Get
            Set
                Me.ped_razonSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_fecha() As String
            Get
                Return Me.ped_fechaField
            End Get
            Set
                Me.ped_fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_total() As Integer
            Get
                Return Me.ped_totalField
            End Get
            Set
                Me.ped_totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_pro_id() As String
            Get
                Return Me.ped_pro_idField
            End Get
            Set
                Me.ped_pro_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pro_descripcion() As String
            Get
                Return Me.pro_descripcionField
            End Get
            Set
                Me.pro_descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_precio() As Decimal
            Get
                Return Me.ped_precioField
            End Get
            Set
                Me.ped_precioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_cantidad() As Integer
            Get
                Return Me.ped_cantidadField
            End Get
            Set
                Me.ped_cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ped_subTotal() As Decimal
            Get
                Return Me.ped_subTotalField
            End Get
            Set
                Me.ped_subTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property situacion() As String
            Get
                Return Me.situacionField
            End Get
            Set
                Me.situacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property desEstado() As String
            Get
                Return Me.desEstadoField
            End Get
            Set
                Me.desEstadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idUsuario() As Integer
            Get
                Return Me.idUsuarioField
            End Get
            Set
                Me.idUsuarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub PedidoListadoCompletedEventHandler(ByVal sender As Object, ByVal e As PedidoListadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PedidoListadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Epedido()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Epedido())
            End Get
        End Property
    End Class
End Namespace
